apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-bruker-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  ingresses:
    - https://ag-notifikasjon-bruker-api.intern.dev.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  tokenx:
    enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: bruker-model
            envVarPrefix: DB
            users:
              - name: bruker-api-kafka-user
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
        - application: tiltaksgjennomforing
          namespace: arbeidsgiver
        - application: aareg-innsyn-arbeidsgiver
          namespace: arbeidsforhold
        - application: sykefravarsstatistikk
          namespace: arbeidsgiver
        - application: min-ia
          namespace: teamia
        - application: forebyggingsplan-frontend
          namespace: teamia
        - application: presenterte-kandidater
          namespace: toi
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: narmesteleder
          namespace: teamsykmelding
      external:
        - host: fakedings.intern.dev.nav.no # fakedings login
        - host: api-gw-q1.oera.no # fallback for altinn-rettigheter-proxy-client
        - host: ereg-services-q1.dev-fss-pub.nais.io # ereg brukes i bruker-api
  envFrom:
    - secret: notifikasjon-bruker-api-secrets

