apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  ingresses:
    - https://ag-notifikasjon-produsent-api.dev.nav.no/
    - https://ag-notifikasjon-produsent-api.dev.intern.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: produsent-model
            envVarPrefix: DB
  accessPolicy:
    outbound:
      external:
        - host: fakedings.dev-gcp.nais.io
        - host: tt02.altinn.no
    inbound:
      rules:
        - application: notifikasjon-test-produsent

        - application: tiltak-refusjon-api
          namespace: arbeidsgiver
          cluster: dev-gcp

        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-fss

        - application: esyfovarsel
          namespace: team-esyfo
          cluster: dev-gcp

        - application: permitteringsmelding-notifikasjon
          namespace: permittering-og-nedbemanning
          cluster: dev-gcp

        - application: fritakagp
          namespace: helsearbeidsgiver
          cluster: dev-gcp

        - application: im-notifikasjon
          namespace: helsearbeidsgiver
          cluster: dev-gcp
  envFrom:
    - secret: notifikasjon-produsent-api-secrets