apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
    subteam: msa
spec:
  image: {{image}}
  ingresses:
    - https://ag-notifikasjon-produsent-api.dev.nav.no/
    - https://ag-notifikasjon-bruker-api.dev.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskSize: 20
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: ag-notifikasjon-query
            envVarPrefix: DB
  accessPolicy:
    outbound:
      external:
        - host: fakedings.dev-gcp.nais.io
        - host: arbeidsgiver.dev.nav.no
        - host: navtestb2c.b2clogin.com

  envFrom:
    - secret: notifikasjon-produsent-api-secrets