apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: notifikasjon
  namespace: fager
  labels:
    team: fager
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 20
    retentionBytes: -1
    retentionHours: -1
  acl:
    - application: notifikasjon-produsent-api
      team: fager
      access: readwrite
    - application: notifikasjon-bruker-api
      team: fager
      access: readwrite
