apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: notifikasjon
  namespace: fager
  labels:
    team: fager
spec:
  pool: {{{ pool }}}
  config:
    cleanupPolicy: compact
    replication: 3
    minimumInSyncReplicas: 2
    partitions: 20
    retentionBytes: -1
    retentionHours: -1
  acl:
    - application: notifikasjon-produsent-api
      team: fager
      access: readwrite
    - application: notifikasjon-bruker-api
      team: fager
      access: readwrite
    - application: notifikasjon-kafka-reaper
      team: fager
      access: readwrite
    - application: notifikasjon-statistikk
      team: fager
      access: read
    - application: notifikasjon-ekstern-varsling
      team: fager
      access: readwrite
    - application: notifikasjon-replay-validator
      team: fager
      access: read
    - application: notifikasjon-devops
      team: fager
      access: readwrite
    - application: notifikasjon-autoslett
      team: fager
      access: readwrite
    - application: notifikasjon-kafka-backup
      team: fager
      access: read
    - application: notifikasjon-skedulert-utgaatt
      team: fager
      access: readwrite
