apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-bruker-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  replicas:
    max: 24
  ingresses:
    - https://ag-notifikasjon-bruker-api.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  tokenx:
    enabled: true
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: true
        databases:
          - name: bruker-model
            envVarPrefix: DB
            users:
              - name: bruker-api-kafka-user
        autoBackupHour: 1
        maintenance:
          hour: 3
  accessPolicy:
    inbound:
      rules:
        - application: min-side-arbeidsgiver
        - application: tiltaksgjennomforing
          namespace: arbeidsgiver
        - application: aareg-innsyn-arbeidsgiver
          namespace: arbeidsforhold
        - application: sykefravarsstatistikk
          namespace: arbeidsgiver
        - application: min-ia
          namespace: teamia
        - application: forebyggingsplan-frontend
          namespace: teamia
        - application: presenterte-kandidater
          namespace: toi
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
      external:
        - host: api-gw.oera.no # fallback for altinn-rettigheter-proxy-client
        - host: ereg-services.prod-fss-pub.nais.io # ereg brukes i bruker-api
  env:
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
  envFrom:
    - secret: notifikasjon-bruker-api-secrets
