apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-replay-validator
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 1000m
      memory: 512Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-prod
  env:
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"