apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-ekstern-varsling
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 5000m # https://home.robusta.dev/blog/stop-using-cpu-limits/
      memory: 1024Mi
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: altinn-varsel-firewall
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskAutoresize: true
        databases:
          - name: ekstern-varsling-model
            envVarPrefix: DB
        autoBackupHour: 1
        maintenance:
          hour: 3
  env:
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
  envFrom:
    - secret: altinn-basic-ws
